proxies:
  - name: IDAMP
    server: 104.22.64.181
    port: 443
    type: vmess
    uuid: 49acef15-2452-4736-a17d-78bdd3a996ee
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-amp-id01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vmess-ws/messpedo-globalssh
      headers:
        Host: vmess-amp-id01.globalssh.xyz
    udp: true
