proxies:
  - name: FREE01
    server: 104.22.64.181
    port: 80
    type: vmess
    uuid: 47517491-8be8-413c-bda8-68651fea0199
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sgl-1.herbalv2ray.me
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: sgl-1.herbalv2ray.me
    udp: true
  - name: SGCTB
    server: 104.22.64.181
    port: 443
    type: vmess
    uuid: 92f859a2-f8ac-4b3a-a291-7a0b30435b17
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-ctb-sg01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vmess-ws/pedidu-globalssh
      headers:
        Host: vmess-ctb-sg01.globalssh.xyz
    udp: true
  - name: SGOVH
    server: 104.22.64.181
    port: 443
    type: vmess
    uuid: 5ecb740b-f004-4c6f-90fd-30cbe6596f04
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vmess-ovh-sg01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vmess-ws/ovhpedo-globalssh
      headers:
        Host: vmess-ovh-sg01.globalssh.xyz
    udp: true
  - name: VIP01
    server: 104.22.64.181
    port: 443
    type: vmess
    uuid: 20eed4b4-428c-4efe-8a11-525751ca5461
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: vip13.globalssh.com
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vip13.globalssh.com
    udp: true
  - name: opentunnel.net-pedoyada
    server: 104.22.64.181
    port: 443
    type: vmess
    uuid: a40d34c6-b77c-4648-9210-3e8d2f4226b5
    alterId: 16
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sgv-2.openv2ray.com
    network: ws
    ws-opts:
      path: /u/opentunnel.net-pedoyada
      headers:
        Host: sgv-2.openv2ray.com
    udp: true
